Hi ma'am, i have added more screenshots of app, please merge it
SaumyaSingh1/Fitofy-India pull request #10
Opened 2019-12-16 16:48 UTC by amit6663

2019-12-18 03:30 UTC, SaumyaSingh1 commented
@amit6663  great work

2019-12-18 03:32 UTC, SaumyaSingh1 commented
just few more changes and you will earn your first reward .

2019-12-18 03:34 UTC, saumya1singh requested changes

2019-12-18 03:34 UTC, SaumyaSingh1 commented on README.md
> +# Here are all screenshots of the application
change all to some @amit6663

2019-12-18 03:34 UTC, SaumyaSingh1 commented on README.md
> +
@amit6663  change the image sizes . it's looking quite big . make it look small and concised .

2019-12-18 14:46 UTC, SaumyaSingh1 commented
@amit6663  well done , your work is very appreciating 🎉

2019-12-18 14:47 UTC, SaumyaSingh1 commented
@amit6663  I will approve your changes just after a quick review .

2019-12-18 15:53 UTC, SaumyaSingh1 commented
@amit6663  I want you to remove some of the screens from screenshots that are not well designed.
I am writing the picture number which you have to remove : 7,11,12,13,14,16,17,18,19,23,24,28 ,26,27 .

When you guys will work on improving the screens then we will add more SS . 

And last thing is  squash your commits into one commit .

Then i will approve your changes and you will earn your point for KOSS contest .

2019-12-18 18:53 UTC, amit6663 commented
I have done ma'am please look again, @SaumyaSingh1

2019-12-20 14:57 UTC, SaumyaSingh1 commented
You will be rewarded once I approve @amit6663

2019-12-20 14:57 UTC, saumya1singh approved these changes

2019-12-20 14:58 UTC, SaumyaSingh1 commented
@amit6663 approved 🎉

2019-12-26 07:52 UTC, closed without merging